language: python
sudo: true
before_install:
  - ./.travis.tmux.sh

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"

matrix:
    allow_failures:
        - python: "pypy"

install:
    - "pip install blessings==1.6 termcast-client==0.1.3 tmuxp==0.8.1 ipython==3.2.1 nose==1.3.7 flaky==2.1.1"

script:
    - ./.travis.script.sh
